# Generated by Django 5.2.11 on 2026-02-19 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Postupleny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_numksu', models.CharField(blank=True, max_length=200, null=True, verbose_name='Год и номер записи в КСУ')),
                ('num_akt', models.CharField(blank=True, max_length=200, null=True, verbose_name='Номер акта индивидуального учета')),
                ('create_date', models.DateTimeField(auto_now=True, verbose_name='Дата')),
                ('num_sop_doc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Номер сопроводительного документа')),
                ('istochnic_c', models.CharField(blank=True, max_length=200, null=True, verbose_name='Источник комплектования (КОД)')),
                ('num_order', models.CharField(blank=True, max_length=200, null=True, verbose_name='Номер заказа')),
                ('date_naimen', models.CharField(blank=True, max_length=200, null=True, verbose_name='Число наименований')),
                ('date_ekzam', models.CharField(blank=True, max_length=200, null=True, verbose_name='Число экземпляров')),
                ('price', models.CharField(blank=True, max_length=200, null=True, verbose_name='На сумму')),
                ('cost', models.CharField(blank=True, max_length=200, null=True, verbose_name='Платно/бесплатно')),
                ('nds', models.CharField(blank=True, max_length=200, null=True, verbose_name='В том числе - НДС')),
            ],
        ),
        migrations.CreateModel(
            name='Levelwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levelwork', models.CharField(choices=[('1', 'ПК-Создание записи'), ('2', 'РЗ - Размещение заказа'), ('3', 'ИЗ - Исполнение заказа'), ('4', 'КТ - Каталогизация'), ('5', 'С - Систематизация'), ('6', 'ДК - Докомплектование'), ('7', 'КР - Корректура'), ('8', 'ВБ - Выбытие')], default='1', max_length=2)),
                ('create_date', models.DateTimeField(auto_now=True, verbose_name='Дата')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Zapisksu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sv_zamene', models.CharField(blank=True, max_length=200, null=True, verbose_name=' Сведения о замене утерянных книг')),
                ('levelwork', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='complect.levelwork', verbose_name='Этап работы, дата, ФИО')),
                ('sv_postupleni', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='complect.postupleny', verbose_name='Сведения о поступлении книг в библиотеку')),
            ],
        ),
    ]
