# Generated by Django 5.2.7 on 2026-04-06 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complect', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zapisksu',
            name='levelwork',
        ),
        migrations.RemoveField(
            model_name='zapisksu',
            name='sv_postupleni',
        ),
        migrations.RemoveField(
            model_name='postupleny',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='postupleny',
            name='nds',
        ),
        migrations.RemoveField(
            model_name='postupleny',
            name='num_order',
        ),
        migrations.AddField(
            model_name='postupleny',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postupleny',
            name='istochnic_c',
            field=models.CharField(blank=True, default='НБОшГУ', max_length=200, null=True, verbose_name='Источник комплектования (КОД)'),
        ),
        migrations.AlterField(
            model_name='postupleny',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='На сумму'),
        ),
        migrations.DeleteModel(
            name='Levelwork',
        ),
        migrations.DeleteModel(
            name='Zapisksu',
        ),
    ]
