# Generated by Django 5.2.7 on 2026-04-07 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complect', '0002_remove_zapisksu_levelwork_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RZN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': ' По разделам знаний',
            },
        ),
        migrations.AlterModelOptions(
            name='postupleny',
            options={'verbose_name_plural': 'Сведения о поступлении книг в библиотеку'},
        ),
        migrations.CreateModel(
            name='Raspredeleny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books', models.CharField(blank=True, max_length=200, null=True, verbose_name='Книги на баланс')),
                ('broshur', models.CharField(blank=True, max_length=200, null=True, verbose_name='Брошюры')),
                ('journal', models.CharField(blank=True, max_length=200, null=True, verbose_name='Журналы')),
                ('aud_vid', models.CharField(blank=True, max_length=200, null=True, verbose_name='Аудио/Видео')),
                ('carty', models.CharField(blank=True, max_length=200, null=True, verbose_name='Карты')),
                ('noty', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ноты')),
                ('electron_izd', models.CharField(blank=True, max_length=200, null=True, verbose_name='Электронные издания')),
                ('prochy', models.CharField(blank=True, max_length=200, null=True, verbose_name='Прочие')),
                ('russian', models.CharField(blank=True, max_length=200, null=True, verbose_name='русский язык')),
                ('national', models.CharField(blank=True, max_length=200, null=True, verbose_name='национальный язык')),
                ('other', models.CharField(blank=True, max_length=200, null=True, verbose_name='другой язык')),
                ('bez_periodiki', models.CharField(blank=True, max_length=200, null=True, verbose_name='Всего наименований без периодики')),
                ('all_examp', models.CharField(blank=True, max_length=200, null=True, verbose_name='Всего экземпляров')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Всего на сумму')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='complect.rzn', verbose_name='По разделам знаний')),
            ],
            options={
                'verbose_name_plural': 'Данные распределения партии',
            },
        ),
    ]
