# Generated by Django 5.2.7 on 2026-04-09 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complect', '0004_alter_postupleny_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raspredeleny',
            old_name='price',
            new_name='price1',
        ),
    ]
