# Generated by Django 5.2.7 on 2026-04-09 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complect', '0005_rename_price_raspredeleny_price1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raspredeleny',
            old_name='price1',
            new_name='summa',
        ),
    ]
