# Generated by Django 5.2.7 on 2026-04-13 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complect', '0006_rename_price1_raspredeleny_summa'),
    ]

    operations = [
        migrations.AddField(
            model_name='raspredeleny',
            name='inv_num',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Макс. и мин. инв номера партии'),
        ),
    ]
