# Generated by Django 5.2.7 on 2026-04-16 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complect', '0007_raspredeleny_inv_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='postupleny',
            name='all_examp',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Всего экземпляров'),
        ),
        migrations.AddField(
            model_name='postupleny',
            name='aud_vid',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Аудио/Видео'),
        ),
        migrations.AddField(
            model_name='postupleny',
            name='bez_periodiki',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Всего наименований без периодики'),
        ),
        migrations.AddField(
            model_name='postupleny',
            name='books',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Книги на баланс'),
        ),
        migrations.AddField(
            model_name='postupleny',
            name='broshur',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Брошюры'),
        ),
        migrations.AddField(
            model_name='postupleny',
            name='carty',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Карты'),
        ),
        migrations.AddField(
            model_name='postupleny',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='complect.rzn', verbose_name='По разделам знаний'),
        ),
        migrations.AddField(
            model_name='postupleny',
            name='electron_izd',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Электронные издания'),
        ),
        migrations.AddField(
            model_name='postupleny',
            name='inv_num',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Макс. и мин. инв номера партии'),
        ),
        migrations.AddField(
            model_name='postupleny',
            name='journal',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Журналы'),
        ),
        migrations.AddField(
            model_name='postupleny',
            name='national',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='национальный язык'),
        ),
        migrations.AddField(
            model_name='postupleny',
            name='noty',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ноты'),
        ),
        migrations.AddField(
            model_name='postupleny',
            name='other',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='другой язык'),
        ),
        migrations.AddField(
            model_name='postupleny',
            name='prochy',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Прочие'),
        ),
        migrations.AddField(
            model_name='postupleny',
            name='russian',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='русский язык'),
        ),
        migrations.DeleteModel(
            name='Raspredeleny',
        ),
    ]
